name: 'Add PR Checks'
description: |
  'Allows you to collect PR status checks from a defined directory as a post step in your build'
inputs:
  token:
    description: 'your GITHUB_TOKEN'
    required: true
  checks-path:
    description: 'The path where we should look for checks (example: ".checks/")'
    required: false
  checks:
    description: 'Checks directly defined in the workflow.yaml that you want to add.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
