name: Pull Request

on:
  pull_request:
    branches: 
      - main

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Verify PR
    runs-on: macos-latest # I want to make sure this runs on macOS

    steps:
      - name: Get app token
        id: ptrk-app
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.PTRK_APP_ID }}
          private_key: ${{ secrets.PTRK_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'
      
      # Checks
      - name: Add PR Checks
        uses: patriknyblad/add-pr-checks@1.0.0-alpha.1
        with:
          token: ${{ steps.ptrk-app.outputs.token }}
          checks-path: "**/sample-checks/*"
